// Importing necessary functions from Redux Toolkit
import { createSlice, nanoid } from "@reduxjs/toolkit";

// Initial state of the todo list, containing a single example todo
const initialState = {
  todos: [{ id: 1, text: "redux" }] // Example todo item
};

// Creating a slice for the todo feature
export const todoSlice = createSlice({
  name: 'todo', // Name of the slice
  initialState, // Initial state for the slice
  reducers: {
    // Reducer to add a new todo item
    addTodo: (state, action) => {
      const todo = {
        id: nanoid(), // Generate a unique ID for the new todo
        text: action.payload, // Use the payload as the text of the todo.
        completed: false // Initialize the completed status to false
      };
      state.todos.push(todo); // Add the new todo to the list
    },
    // Reducer to remove a todo item by its ID
    removeTodo: (state, action) => {
      const id = action.payload; // ID of the todo to be removed
      // Filter out the todo with the matching ID
      state.todos = state.todos.filter((todo) => todo.id !== id);
    },
    // Reducer to update the text of an existing todo
    updateTodo: (state, action) => {
      const { id, text } = action.payload; // Extract ID and new text from the payload
      // Iterate through the todos and update the matching one
      state.todos = state.todos.map((todo) => {
      if (todo.id === id) {
        return { ...todo, text }; // Replace text if ID matches
      }
      return todo; // Keep as it is if ID does not match
      });
    }
    }
  });

// Exporting the actions generated by the slice
export const { addTodo, removeTodo, updateTodo } = todoSlice.actions;

// Exporting the reducer to be used in the store
export default todoSlice.reducer;